### ISSUE TITLE
Mod causes lockups

### ISSUE THREAD

**Issue by xanthian** [BrianComics/Minecraft-Mods#1]
Sadly it does not generate any logs.
MC just freezes, server remains functional.
This only occurs when connected to a server with the mod installed.
Its possible mod is trying to render particles server side which it shouldn't be able to do.

mod list irrelevant as it will do this on its own.

**Comment by BrianComics** [comment]
Sorry for the late response! Does the mod generate any crash reports? I know you said it doesn't generate any logs. I have not been able to reproduce the issue, but I have a pretty good idea what is causing it.

**Comment by xanthian** [comment]
no crash reports.
no logs, client just hangs
however from server log you can see the game continuing to run in the background.

its simple to replicate.
install only Sparkle, open single player world, open to land, change to spectator, fly around underground.

**Comment by BrianComics** [comment]
I think it's because I used a `while` loop that searches for air blocks to spawn the particles. If it can't find a place ( like if the block is completely surrounded by stone ) to spawn the particles, it will just freeze and stop responding. It should be a simple fix. I'll have a new version shortly!

**Comment by BrianComics** [comment]
Hello! I have fixed the bug! Please download the new version from Modrinth. The CurseForge version is still being checked, but it should be done soon!
